#!/usr/bin/env sh

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
ROOT_DIR=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)

PAPERCLIP_VERSION="${PAPERCLIP_VERSION:-2026.318.0}"
PAPERCLIP_HOME="${PAPERCLIP_HOME:-$ROOT_DIR/.paperclip-home}"
PAPERCLIP_INSTANCE_ID="${PAPERCLIP_INSTANCE_ID:-demo}"
PAPERCLIP_CONFIG="${PAPERCLIP_CONFIG:-$PAPERCLIP_HOME/config.json}"
PAPERCLIP_RUNTIME_DIR="${PAPERCLIP_RUNTIME_DIR:-$ROOT_DIR/runtime}"
PAPERCLIP_BIN="${PAPERCLIP_BIN:-$PAPERCLIP_RUNTIME_DIR/node_modules/.bin/paperclipai}"
PAPERCLIP_HOST="${PAPERCLIP_HOST:-127.0.0.1}"
PAPERCLIP_PORT="${PAPERCLIP_PORT:-3100}"
PAPERCLIP_DEPLOYMENT_MODE="${PAPERCLIP_DEPLOYMENT_MODE:-local_trusted}"
PAPERCLIP_DEPLOYMENT_EXPOSURE="${PAPERCLIP_DEPLOYMENT_EXPOSURE:-private}"
PAPERCLIP_PUBLIC_URL="${PAPERCLIP_PUBLIC_URL:-}"
PAPERCLIP_ALLOWED_HOSTNAMES="${PAPERCLIP_ALLOWED_HOSTNAMES:-}"
SERVE_UI="${SERVE_UI:-true}"
PAPERCLIP_REWRITE_FROM_ROOT="${PAPERCLIP_REWRITE_FROM_ROOT:-}"
PAPERCLIP_CANONICAL_PROJECT_ROOT="${PAPERCLIP_CANONICAL_PROJECT_ROOT:-$ROOT_DIR}"
PAPERCLIP_URL="${PAPERCLIP_URL:-http://$PAPERCLIP_HOST:$PAPERCLIP_PORT}"
PAPERCLIP_PID_FILE="${PAPERCLIP_PID_FILE:-$PAPERCLIP_HOME/paperclip.pid}"
PAPERCLIP_LOG_DIR="${PAPERCLIP_LOG_DIR:-$PAPERCLIP_HOME/instances/$PAPERCLIP_INSTANCE_ID/logs}"
PAPERCLIP_LAUNCH_LOG="${PAPERCLIP_LAUNCH_LOG:-$PAPERCLIP_LOG_DIR/launcher.log}"
